services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    build: backend
    restart: always
    networks:
      - react-express
    expose:
      - 3000
    environment:
      - OPENAI_API_KEY="your key here"

networks:
  react-express:
